# Generated by Django 3.1 on 2020-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200909_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('proficient', 'proficient'), ('native', 'native')], max_length=20),
        ),
    ]
