# Generated by Django 3.1 on 2020-09-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_experience_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracurricular_and_hobby',
            old_name='items',
            new_name='item',
        ),
    ]
